import getData from '@/lib/getData';

export type RaceEvent = { type: string; date: string; timezone: string };
export type RaceStatus =
  | 'Live'
  | 'Completed'
  | 'Cancelled'
  | 'Postponed'
  | 'Scheduled';

export type RaceType =
  | 'Race'
  | 'Sprint'
  | '1st Practice'
  | '2nd Practice'
  | '3rd Practice'
  | '1st Qualifying'
  | '2nd Qualifying'
  | '3rd Qualifying';

export type RaceData = {
  id: number;
  competition: {
    id: number;
    name: string;
    location: { country: string; city: string };
  };
  circuit: {
    id: number;
    name: string;
    image: string;
  };
  season: number;
  type: RaceType;
  laps: { current: number | null; total: number | null };
  fastest_lap: { driver: { id: number | null }; time: string | null };
  distance: string | null;
  timezone: string;
  date: string;
  weather: string | null;
  status: RaceStatus;
};

export type MapedRace = RaceData & {
  events: RaceEvent[];
};

export type Race = RaceData & {
  events: RaceEvent[];
  round: number;
};

type GetRaces = { data: Race[] | null; errors: string | null };

export const races: RaceData[] = [
  {
    id: 1488,
    competition: {
      id: 2,
      name: 'Bahrain Grand Prix',
      location: { country: 'Bahrain', city: 'Sakhir' },
    },
    circuit: {
      id: 2,
      name: 'Bahrain International Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/2.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 58 },
    fastest_lap: { driver: { id: 34 }, time: '1:35.558' },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-03-20T15:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1489,
    competition: {
      id: 2,
      name: 'Bahrain Grand Prix',
      location: { country: 'Bahrain', city: 'Sakhir' },
    },
    circuit: {
      id: 2,
      name: 'Bahrain International Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/2.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-19T15:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1490,
    competition: {
      id: 2,
      name: 'Bahrain Grand Prix',
      location: { country: 'Bahrain', city: 'Sakhir' },
    },
    circuit: {
      id: 2,
      name: 'Bahrain International Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/2.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-19T12:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1491,
    competition: {
      id: 2,
      name: 'Bahrain Grand Prix',
      location: { country: 'Bahrain', city: 'Sakhir' },
    },
    circuit: {
      id: 2,
      name: 'Bahrain International Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/2.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-18T15:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1492,
    competition: {
      id: 2,
      name: 'Bahrain Grand Prix',
      location: { country: 'Bahrain', city: 'Sakhir' },
    },
    circuit: {
      id: 2,
      name: 'Bahrain International Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/2.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-18T12:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1493,
    competition: {
      id: 32,
      name: 'Saudi Arabia Grand Prix',
      location: { country: 'Saudi Arabia ', city: 'Djeddah' },
    },
    circuit: {
      id: 29,
      name: 'Jeddah Corniche Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/29.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 58 },
    fastest_lap: { driver: { id: 34 }, time: '1:31.634' },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-03-27T17:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1494,
    competition: {
      id: 32,
      name: 'Saudi Arabia Grand Prix',
      location: { country: 'Saudi Arabia ', city: 'Djeddah' },
    },
    circuit: {
      id: 29,
      name: 'Jeddah Corniche Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/29.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-26T17:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1495,
    competition: {
      id: 32,
      name: 'Saudi Arabia Grand Prix',
      location: { country: 'Saudi Arabia ', city: 'Djeddah' },
    },
    circuit: {
      id: 29,
      name: 'Jeddah Corniche Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/29.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-26T14:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1496,
    competition: {
      id: 32,
      name: 'Saudi Arabia Grand Prix',
      location: { country: 'Saudi Arabia ', city: 'Djeddah' },
    },
    circuit: {
      id: 29,
      name: 'Jeddah Corniche Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/29.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-25T17:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1497,
    competition: {
      id: 32,
      name: 'Saudi Arabia Grand Prix',
      location: { country: 'Saudi Arabia ', city: 'Djeddah' },
    },
    circuit: {
      id: 29,
      name: 'Jeddah Corniche Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/29.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-25T14:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1498,
    competition: {
      id: 1,
      name: 'Australia Grand Prix',
      location: { country: 'Australia', city: 'Melbourne' },
    },
    circuit: {
      id: 1,
      name: 'Albert Park Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/1.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 58 },
    fastest_lap: { driver: { id: 34 }, time: '1:21.868' },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-04-10T05:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1499,
    competition: {
      id: 1,
      name: 'Australia Grand Prix',
      location: { country: 'Australia', city: 'Melbourne' },
    },
    circuit: {
      id: 1,
      name: 'Albert Park Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/1.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-09T06:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1500,
    competition: {
      id: 1,
      name: 'Australia Grand Prix',
      location: { country: 'Australia', city: 'Melbourne' },
    },
    circuit: {
      id: 1,
      name: 'Albert Park Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/1.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-09T03:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1501,
    competition: {
      id: 1,
      name: 'Australia Grand Prix',
      location: { country: 'Australia', city: 'Melbourne' },
    },
    circuit: {
      id: 1,
      name: 'Albert Park Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/1.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-08T06:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1502,
    competition: {
      id: 1,
      name: 'Australia Grand Prix',
      location: { country: 'Australia', city: 'Melbourne' },
    },
    circuit: {
      id: 1,
      name: 'Albert Park Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/1.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-08T03:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1503,
    competition: {
      id: 29,
      name: 'Emilia Romagna Grand Prix',
      location: { country: 'Italy', city: 'Imola' },
    },
    circuit: {
      id: 27,
      name: 'Autodromo Enzo e Dino Ferrari',
      image: 'https://media.api-sports.io/formula-1/circuits/27.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 57 },
    fastest_lap: { driver: { id: 25 }, time: '1:18.457' },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-04-24T13:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1504,
    competition: {
      id: 29,
      name: 'Emilia Romagna Grand Prix',
      location: { country: 'Italy', city: 'Imola' },
    },
    circuit: {
      id: 27,
      name: 'Autodromo Enzo e Dino Ferrari',
      image: 'https://media.api-sports.io/formula-1/circuits/27.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-22T15:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1505,
    competition: {
      id: 29,
      name: 'Emilia Romagna Grand Prix',
      location: { country: 'Italy', city: 'Imola' },
    },
    circuit: {
      id: 27,
      name: 'Autodromo Enzo e Dino Ferrari',
      image: 'https://media.api-sports.io/formula-1/circuits/27.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-22T10:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1506,
    competition: {
      id: 29,
      name: 'Emilia Romagna Grand Prix',
      location: { country: 'Italy', city: 'Imola' },
    },
    circuit: {
      id: 27,
      name: 'Autodromo Enzo e Dino Ferrari',
      image: 'https://media.api-sports.io/formula-1/circuits/27.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-23T10:30:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1507,
    competition: {
      id: 29,
      name: 'Emilia Romagna Grand Prix',
      location: { country: 'Italy', city: 'Imola' },
    },
    circuit: {
      id: 27,
      name: 'Autodromo Enzo e Dino Ferrari',
      image: 'https://media.api-sports.io/formula-1/circuits/27.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-22T11:30:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1508,
    competition: {
      id: 34,
      name: 'Miami Grand Prix',
      location: { country: 'USA', city: 'Miami' },
    },
    circuit: {
      id: 31,
      name: 'Miami International Autodrome',
      image: 'https://media.api-sports.io/formula-1/circuits/31.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 57 },
    fastest_lap: { driver: { id: 25 }, time: '1:31.361' },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-05-08T19:30:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1509,
    competition: {
      id: 34,
      name: 'Miami Grand Prix',
      location: { country: 'USA', city: 'Miami' },
    },
    circuit: {
      id: 31,
      name: 'Miami International Autodrome',
      image: 'https://media.api-sports.io/formula-1/circuits/31.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-07T20:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1510,
    competition: {
      id: 34,
      name: 'Miami Grand Prix',
      location: { country: 'USA', city: 'Miami' },
    },
    circuit: {
      id: 31,
      name: 'Miami International Autodrome',
      image: 'https://media.api-sports.io/formula-1/circuits/31.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-07T17:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1511,
    competition: {
      id: 34,
      name: 'Miami Grand Prix',
      location: { country: 'USA', city: 'Miami' },
    },
    circuit: {
      id: 31,
      name: 'Miami International Autodrome',
      image: 'https://media.api-sports.io/formula-1/circuits/31.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-06T21:30:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1512,
    competition: {
      id: 34,
      name: 'Miami Grand Prix',
      location: { country: 'USA', city: 'Miami' },
    },
    circuit: {
      id: 31,
      name: 'Miami International Autodrome',
      image: 'https://media.api-sports.io/formula-1/circuits/31.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-06T18:30:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1513,
    competition: {
      id: 6,
      name: 'Spain Grand Prix',
      location: { country: 'Spain', city: ' Montmeló' },
    },
    circuit: {
      id: 6,
      name: 'Circuit de Barcelona-Catalunya',
      image: 'https://media.api-sports.io/formula-1/circuits/6.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 57 },
    fastest_lap: { driver: { id: 10 }, time: '1:24.108' },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-05-22T13:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1514,
    competition: {
      id: 6,
      name: 'Spain Grand Prix',
      location: { country: 'Spain', city: ' Montmeló' },
    },
    circuit: {
      id: 6,
      name: 'Circuit de Barcelona-Catalunya',
      image: 'https://media.api-sports.io/formula-1/circuits/6.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-21T14:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1515,
    competition: {
      id: 6,
      name: 'Spain Grand Prix',
      location: { country: 'Spain', city: ' Montmeló' },
    },
    circuit: {
      id: 6,
      name: 'Circuit de Barcelona-Catalunya',
      image: 'https://media.api-sports.io/formula-1/circuits/6.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-21T11:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1516,
    competition: {
      id: 6,
      name: 'Spain Grand Prix',
      location: { country: 'Spain', city: ' Montmeló' },
    },
    circuit: {
      id: 6,
      name: 'Circuit de Barcelona-Catalunya',
      image: 'https://media.api-sports.io/formula-1/circuits/6.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-20T15:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1517,
    competition: {
      id: 6,
      name: 'Spain Grand Prix',
      location: { country: 'Spain', city: ' Montmeló' },
    },
    circuit: {
      id: 6,
      name: 'Circuit de Barcelona-Catalunya',
      image: 'https://media.api-sports.io/formula-1/circuits/6.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-20T12:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1518,
    competition: {
      id: 7,
      name: 'Monaco Grand Prix',
      location: { country: 'Monaco', city: 'Monte-Carlo' },
    },
    circuit: {
      id: 7,
      name: 'Circuit de Monaco',
      image: 'https://media.api-sports.io/formula-1/circuits/7.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 78 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-05-29T13:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1519,
    competition: {
      id: 7,
      name: 'Monaco Grand Prix',
      location: { country: 'Monaco', city: 'Monte-Carlo' },
    },
    circuit: {
      id: 7,
      name: 'Circuit de Monaco',
      image: 'https://media.api-sports.io/formula-1/circuits/7.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-28T14:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1520,
    competition: {
      id: 7,
      name: 'Monaco Grand Prix',
      location: { country: 'Monaco', city: 'Monte-Carlo' },
    },
    circuit: {
      id: 7,
      name: 'Circuit de Monaco',
      image: 'https://media.api-sports.io/formula-1/circuits/7.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-28T11:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1521,
    competition: {
      id: 7,
      name: 'Monaco Grand Prix',
      location: { country: 'Monaco', city: 'Monte-Carlo' },
    },
    circuit: {
      id: 7,
      name: 'Circuit de Monaco',
      image: 'https://media.api-sports.io/formula-1/circuits/7.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-27T15:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1522,
    competition: {
      id: 7,
      name: 'Monaco Grand Prix',
      location: { country: 'Monaco', city: 'Monte-Carlo' },
    },
    circuit: {
      id: 7,
      name: 'Circuit de Monaco',
      image: 'https://media.api-sports.io/formula-1/circuits/7.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-27T12:00:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1523,
    competition: {
      id: 8,
      name: 'Azerbaijan Grand Prix',
      location: { country: 'Azerbaijan', city: 'Bakou' },
    },
    circuit: {
      id: 8,
      name: 'Baku City Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/8.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 51 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-06-12T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1524,
    competition: {
      id: 8,
      name: 'Azerbaijan Grand Prix',
      location: { country: 'Azerbaijan', city: 'Bakou' },
    },
    circuit: {
      id: 8,
      name: 'Baku City Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/8.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-06-11T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1525,
    competition: {
      id: 8,
      name: 'Azerbaijan Grand Prix',
      location: { country: 'Azerbaijan', city: 'Bakou' },
    },
    circuit: {
      id: 8,
      name: 'Baku City Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/8.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-06-11T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1526,
    competition: {
      id: 8,
      name: 'Azerbaijan Grand Prix',
      location: { country: 'Azerbaijan', city: 'Bakou' },
    },
    circuit: {
      id: 8,
      name: 'Baku City Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/8.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-06-10T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1527,
    competition: {
      id: 8,
      name: 'Azerbaijan Grand Prix',
      location: { country: 'Azerbaijan', city: 'Bakou' },
    },
    circuit: {
      id: 8,
      name: 'Baku City Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/8.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-06-10T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1528,
    competition: {
      id: 9,
      name: 'Canada Grand Prix',
      location: { country: 'Canada', city: 'Montréal' },
    },
    circuit: {
      id: 9,
      name: 'Circuit Gilles-Villeneuve',
      image: 'https://media.api-sports.io/formula-1/circuits/9.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 68 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '305.3 Kms',
    timezone: 'utc',
    date: '2022-06-19T18:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1529,
    competition: {
      id: 9,
      name: 'Canada Grand Prix',
      location: { country: 'Canada', city: 'Montréal' },
    },
    circuit: {
      id: 9,
      name: 'Circuit Gilles-Villeneuve',
      image: 'https://media.api-sports.io/formula-1/circuits/9.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-06-18T20:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1530,
    competition: {
      id: 9,
      name: 'Canada Grand Prix',
      location: { country: 'Canada', city: 'Montréal' },
    },
    circuit: {
      id: 9,
      name: 'Circuit Gilles-Villeneuve',
      image: 'https://media.api-sports.io/formula-1/circuits/9.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-06-18T17:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1531,
    competition: {
      id: 9,
      name: 'Canada Grand Prix',
      location: { country: 'Canada', city: 'Montréal' },
    },
    circuit: {
      id: 9,
      name: 'Circuit Gilles-Villeneuve',
      image: 'https://media.api-sports.io/formula-1/circuits/9.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-06-17T21:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1532,
    competition: {
      id: 9,
      name: 'Canada Grand Prix',
      location: { country: 'Canada', city: 'Montréal' },
    },
    circuit: {
      id: 9,
      name: 'Circuit Gilles-Villeneuve',
      image: 'https://media.api-sports.io/formula-1/circuits/9.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-06-17T18:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1533,
    competition: {
      id: 12,
      name: 'Great Britain Grand Prix',
      location: {
        country: 'Great Britain',
        city: 'Silverstone Northamptonshire',
      },
    },
    circuit: {
      id: 12,
      name: 'Silverstone Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/12.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 52 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '308.4 Kms',
    timezone: 'utc',
    date: '2022-07-03T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1534,
    competition: {
      id: 12,
      name: 'Great Britain Grand Prix',
      location: {
        country: 'Great Britain',
        city: 'Silverstone Northamptonshire',
      },
    },
    circuit: {
      id: 12,
      name: 'Silverstone Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/12.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-02T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1535,
    competition: {
      id: 12,
      name: 'Great Britain Grand Prix',
      location: {
        country: 'Great Britain',
        city: 'Silverstone Northamptonshire',
      },
    },
    circuit: {
      id: 12,
      name: 'Silverstone Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/12.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-02T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1536,
    competition: {
      id: 12,
      name: 'Great Britain Grand Prix',
      location: {
        country: 'Great Britain',
        city: 'Silverstone Northamptonshire',
      },
    },
    circuit: {
      id: 12,
      name: 'Silverstone Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/12.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-01T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1537,
    competition: {
      id: 12,
      name: 'Great Britain Grand Prix',
      location: {
        country: 'Great Britain',
        city: 'Silverstone Northamptonshire',
      },
    },
    circuit: {
      id: 12,
      name: 'Silverstone Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/12.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-01T12:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1538,
    competition: {
      id: 11,
      name: 'Austria Grand Prix',
      location: { country: 'Austria', city: 'Spielberg' },
    },
    circuit: {
      id: 11,
      name: 'Red Bull Ring',
      image: 'https://media.api-sports.io/formula-1/circuits/11.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 71 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '308.4 Kms',
    timezone: 'utc',
    date: '2022-07-10T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1539,
    competition: {
      id: 11,
      name: 'Austria Grand Prix',
      location: { country: 'Austria', city: 'Spielberg' },
    },
    circuit: {
      id: 11,
      name: 'Red Bull Ring',
      image: 'https://media.api-sports.io/formula-1/circuits/11.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-09T10:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1540,
    competition: {
      id: 11,
      name: 'Austria Grand Prix',
      location: { country: 'Austria', city: 'Spielberg' },
    },
    circuit: {
      id: 11,
      name: 'Red Bull Ring',
      image: 'https://media.api-sports.io/formula-1/circuits/11.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-09T10:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1541,
    competition: {
      id: 11,
      name: 'Austria Grand Prix',
      location: { country: 'Austria', city: 'Spielberg' },
    },
    circuit: {
      id: 11,
      name: 'Red Bull Ring',
      image: 'https://media.api-sports.io/formula-1/circuits/11.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-08T10:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1542,
    competition: {
      id: 11,
      name: 'Austria Grand Prix',
      location: { country: 'Austria', city: 'Spielberg' },
    },
    circuit: {
      id: 11,
      name: 'Red Bull Ring',
      image: 'https://media.api-sports.io/formula-1/circuits/11.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-08T10:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1543,
    competition: {
      id: 10,
      name: 'France Grand Prix',
      location: { country: 'France', city: 'Le Castellet' },
    },
    circuit: {
      id: 10,
      name: 'Circuit Paul Ricard',
      image: 'https://media.api-sports.io/formula-1/circuits/10.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 53 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '305.2 Kms',
    timezone: 'utc',
    date: '2022-07-24T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1544,
    competition: {
      id: 10,
      name: 'France Grand Prix',
      location: { country: 'France', city: 'Le Castellet' },
    },
    circuit: {
      id: 10,
      name: 'Circuit Paul Ricard',
      image: 'https://media.api-sports.io/formula-1/circuits/10.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-23T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1545,
    competition: {
      id: 10,
      name: 'France Grand Prix',
      location: { country: 'France', city: 'Le Castellet' },
    },
    circuit: {
      id: 10,
      name: 'Circuit Paul Ricard',
      image: 'https://media.api-sports.io/formula-1/circuits/10.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-23T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1546,
    competition: {
      id: 10,
      name: 'France Grand Prix',
      location: { country: 'France', city: 'Le Castellet' },
    },
    circuit: {
      id: 10,
      name: 'Circuit Paul Ricard',
      image: 'https://media.api-sports.io/formula-1/circuits/10.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-22T15:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1547,
    competition: {
      id: 10,
      name: 'France Grand Prix',
      location: { country: 'France', city: 'Le Castellet' },
    },
    circuit: {
      id: 10,
      name: 'Circuit Paul Ricard',
      image: 'https://media.api-sports.io/formula-1/circuits/10.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-22T12:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1548,
    competition: {
      id: 14,
      name: 'Hungary Grand Prix',
      location: { country: 'Hungary', city: 'Mogyoród' },
    },
    circuit: {
      id: 14,
      name: 'Hungaroring',
      image: 'https://media.api-sports.io/formula-1/circuits/14.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 70 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '306.6 Kms',
    timezone: 'utc',
    date: '2022-08-31T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1549,
    competition: {
      id: 14,
      name: 'Hungary Grand Prix',
      location: { country: 'Hungary', city: 'Mogyoród' },
    },
    circuit: {
      id: 14,
      name: 'Hungaroring',
      image: 'https://media.api-sports.io/formula-1/circuits/14.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-30T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1550,
    competition: {
      id: 14,
      name: 'Hungary Grand Prix',
      location: { country: 'Hungary', city: 'Mogyoród' },
    },
    circuit: {
      id: 14,
      name: 'Hungaroring',
      image: 'https://media.api-sports.io/formula-1/circuits/14.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-30T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1551,
    competition: {
      id: 14,
      name: 'Hungary Grand Prix',
      location: { country: 'Hungary', city: 'Mogyoród' },
    },
    circuit: {
      id: 14,
      name: 'Hungaroring',
      image: 'https://media.api-sports.io/formula-1/circuits/14.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-29T15:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1552,
    competition: {
      id: 14,
      name: 'Hungary Grand Prix',
      location: { country: 'Hungary', city: 'Mogyoród' },
    },
    circuit: {
      id: 14,
      name: 'Hungaroring',
      image: 'https://media.api-sports.io/formula-1/circuits/14.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-07-29T12:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1553,
    competition: {
      id: 15,
      name: 'Belgium Grand Prix',
      location: { country: 'Belgium', city: 'Francorchamps' },
    },
    circuit: {
      id: 15,
      name: 'Circuit de Spa-Francorchamps',
      image: 'https://media.api-sports.io/formula-1/circuits/15.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 44 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '308.1 Kms',
    timezone: 'utc',
    date: '2022-08-28T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1554,
    competition: {
      id: 15,
      name: 'Belgium Grand Prix',
      location: { country: 'Belgium', city: 'Francorchamps' },
    },
    circuit: {
      id: 15,
      name: 'Circuit de Spa-Francorchamps',
      image: 'https://media.api-sports.io/formula-1/circuits/15.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-08-27T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1555,
    competition: {
      id: 15,
      name: 'Belgium Grand Prix',
      location: { country: 'Belgium', city: 'Francorchamps' },
    },
    circuit: {
      id: 15,
      name: 'Circuit de Spa-Francorchamps',
      image: 'https://media.api-sports.io/formula-1/circuits/15.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-08-27T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1556,
    competition: {
      id: 15,
      name: 'Belgium Grand Prix',
      location: { country: 'Belgium', city: 'Francorchamps' },
    },
    circuit: {
      id: 15,
      name: 'Circuit de Spa-Francorchamps',
      image: 'https://media.api-sports.io/formula-1/circuits/15.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-08-26T15:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1557,
    competition: {
      id: 15,
      name: 'Belgium Grand Prix',
      location: { country: 'Belgium', city: 'Francorchamps' },
    },
    circuit: {
      id: 15,
      name: 'Circuit de Spa-Francorchamps',
      image: 'https://media.api-sports.io/formula-1/circuits/15.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-08-26T12:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1558,
    competition: {
      id: 5,
      name: 'Netherlands Grand Prix',
      location: { country: 'Netherlands', city: 'Zandvoort' },
    },
    circuit: {
      id: 5,
      name: 'Circuit Zandvoort',
      image: 'https://media.api-sports.io/formula-1/circuits/5.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 70 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '308.1 Kms',
    timezone: 'utc',
    date: '2022-09-04T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1559,
    competition: {
      id: 5,
      name: 'Netherlands Grand Prix',
      location: { country: 'Netherlands', city: 'Zandvoort' },
    },
    circuit: {
      id: 5,
      name: 'Circuit Zandvoort',
      image: 'https://media.api-sports.io/formula-1/circuits/5.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-03T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1560,
    competition: {
      id: 5,
      name: 'Netherlands Grand Prix',
      location: { country: 'Netherlands', city: 'Zandvoort' },
    },
    circuit: {
      id: 5,
      name: 'Circuit Zandvoort',
      image: 'https://media.api-sports.io/formula-1/circuits/5.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-03T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1561,
    competition: {
      id: 5,
      name: 'Netherlands Grand Prix',
      location: { country: 'Netherlands', city: 'Zandvoort' },
    },
    circuit: {
      id: 5,
      name: 'Circuit Zandvoort',
      image: 'https://media.api-sports.io/formula-1/circuits/5.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-02T15:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1562,
    competition: {
      id: 5,
      name: 'Netherlands Grand Prix',
      location: { country: 'Netherlands', city: 'Zandvoort' },
    },
    circuit: {
      id: 5,
      name: 'Circuit Zandvoort',
      image: 'https://media.api-sports.io/formula-1/circuits/5.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-02T12:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1563,
    competition: {
      id: 16,
      name: 'Italy Grand Prix',
      location: { country: 'Italy', city: 'Monza' },
    },
    circuit: {
      id: 16,
      name: 'Autodromo Nazionale Monza',
      image: 'https://media.api-sports.io/formula-1/circuits/16.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 53 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '306.7 Kms',
    timezone: 'utc',
    date: '2022-09-11T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1564,
    competition: {
      id: 16,
      name: 'Italy Grand Prix',
      location: { country: 'Italy', city: 'Monza' },
    },
    circuit: {
      id: 16,
      name: 'Autodromo Nazionale Monza',
      image: 'https://media.api-sports.io/formula-1/circuits/16.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-10T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1565,
    competition: {
      id: 16,
      name: 'Italy Grand Prix',
      location: { country: 'Italy', city: 'Monza' },
    },
    circuit: {
      id: 16,
      name: 'Autodromo Nazionale Monza',
      image: 'https://media.api-sports.io/formula-1/circuits/16.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-10T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1566,
    competition: {
      id: 16,
      name: 'Italy Grand Prix',
      location: { country: 'Italy', city: 'Monza' },
    },
    circuit: {
      id: 16,
      name: 'Autodromo Nazionale Monza',
      image: 'https://media.api-sports.io/formula-1/circuits/16.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-09T15:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1567,
    competition: {
      id: 16,
      name: 'Italy Grand Prix',
      location: { country: 'Italy', city: 'Monza' },
    },
    circuit: {
      id: 16,
      name: 'Autodromo Nazionale Monza',
      image: 'https://media.api-sports.io/formula-1/circuits/16.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-09T12:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1568,
    competition: {
      id: 18,
      name: 'Russia Grand Prix',
      location: { country: 'Russia', city: 'Sochi' },
    },
    circuit: {
      id: 18,
      name: 'Sochi Autodrom',
      image: 'https://media.api-sports.io/formula-1/circuits/18.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 53 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '305.2 Kms',
    timezone: 'utc',
    date: '2022-09-25T11:00:00+00:00',
    weather: null,
    status: 'Cancelled',
  },
  {
    id: 1569,
    competition: {
      id: 18,
      name: 'Russia Grand Prix',
      location: { country: 'Russia', city: 'Sochi' },
    },
    circuit: {
      id: 18,
      name: 'Sochi Autodrom',
      image: 'https://media.api-sports.io/formula-1/circuits/18.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-24T13:00:00+00:00',
    weather: null,
    status: 'Cancelled',
  },
  {
    id: 1570,
    competition: {
      id: 18,
      name: 'Russia Grand Prix',
      location: { country: 'Russia', city: 'Sochi' },
    },
    circuit: {
      id: 18,
      name: 'Sochi Autodrom',
      image: 'https://media.api-sports.io/formula-1/circuits/18.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-24T10:00:00+00:00',
    weather: null,
    status: 'Cancelled',
  },
  {
    id: 1571,
    competition: {
      id: 18,
      name: 'Russia Grand Prix',
      location: { country: 'Russia', city: 'Sochi' },
    },
    circuit: {
      id: 18,
      name: 'Sochi Autodrom',
      image: 'https://media.api-sports.io/formula-1/circuits/18.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-23T13:00:00+00:00',
    weather: null,
    status: 'Cancelled',
  },
  {
    id: 1572,
    competition: {
      id: 18,
      name: 'Russia Grand Prix',
      location: { country: 'Russia', city: 'Sochi' },
    },
    circuit: {
      id: 18,
      name: 'Sochi Autodrom',
      image: 'https://media.api-sports.io/formula-1/circuits/18.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-23T10:00:00+00:00',
    weather: null,
    status: 'Cancelled',
  },
  {
    id: 1573,
    competition: {
      id: 17,
      name: 'Singapore Grand Prix',
      location: { country: 'Singapore', city: 'Singapour' },
    },
    circuit: {
      id: 17,
      name: 'Marina Bay Street Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/17.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 61 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '309.3 Kms',
    timezone: 'utc',
    date: '2022-10-02T12:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1574,
    competition: {
      id: 17,
      name: 'Singapore Grand Prix',
      location: { country: 'Singapore', city: 'Singapour' },
    },
    circuit: {
      id: 17,
      name: 'Marina Bay Street Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/17.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-01T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1575,
    competition: {
      id: 17,
      name: 'Singapore Grand Prix',
      location: { country: 'Singapore', city: 'Singapour' },
    },
    circuit: {
      id: 17,
      name: 'Marina Bay Street Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/17.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-01T10:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1576,
    competition: {
      id: 17,
      name: 'Singapore Grand Prix',
      location: { country: 'Singapore', city: 'Singapour' },
    },
    circuit: {
      id: 17,
      name: 'Marina Bay Street Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/17.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-30T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1577,
    competition: {
      id: 17,
      name: 'Singapore Grand Prix',
      location: { country: 'Singapore', city: 'Singapour' },
    },
    circuit: {
      id: 17,
      name: 'Marina Bay Street Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/17.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-09-30T10:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1578,
    competition: {
      id: 19,
      name: 'Japan Grand Prix',
      location: { country: 'Japan', city: 'Suzuka' },
    },
    circuit: {
      id: 19,
      name: 'Suzuka International Racing Course',
      image: 'https://media.api-sports.io/formula-1/circuits/19.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 53 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-10-09T05:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1579,
    competition: {
      id: 19,
      name: 'Japan Grand Prix',
      location: { country: 'Japan', city: 'Suzuka' },
    },
    circuit: {
      id: 19,
      name: 'Suzuka International Racing Course',
      image: 'https://media.api-sports.io/formula-1/circuits/19.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-08T07:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1580,
    competition: {
      id: 19,
      name: 'Japan Grand Prix',
      location: { country: 'Japan', city: 'Suzuka' },
    },
    circuit: {
      id: 19,
      name: 'Suzuka International Racing Course',
      image: 'https://media.api-sports.io/formula-1/circuits/19.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-08T04:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1581,
    competition: {
      id: 19,
      name: 'Japan Grand Prix',
      location: { country: 'Japan', city: 'Suzuka' },
    },
    circuit: {
      id: 19,
      name: 'Suzuka International Racing Course',
      image: 'https://media.api-sports.io/formula-1/circuits/19.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-07T07:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1582,
    competition: {
      id: 19,
      name: 'Japan Grand Prix',
      location: { country: 'Japan', city: 'Suzuka' },
    },
    circuit: {
      id: 19,
      name: 'Suzuka International Racing Course',
      image: 'https://media.api-sports.io/formula-1/circuits/19.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-07T04:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1583,
    competition: {
      id: 20,
      name: 'USA Grand Prix',
      location: { country: 'USA', city: 'Elroy' },
    },
    circuit: {
      id: 20,
      name: 'Circuit of The Americas',
      image: 'https://media.api-sports.io/formula-1/circuits/20.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 56 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '308.9 Kms',
    timezone: 'utc',
    date: '2022-10-23T19:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1584,
    competition: {
      id: 20,
      name: 'USA Grand Prix',
      location: { country: 'USA', city: 'Elroy' },
    },
    circuit: {
      id: 20,
      name: 'Circuit of The Americas',
      image: 'https://media.api-sports.io/formula-1/circuits/20.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-22T22:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1585,
    competition: {
      id: 20,
      name: 'USA Grand Prix',
      location: { country: 'USA', city: 'Elroy' },
    },
    circuit: {
      id: 20,
      name: 'Circuit of The Americas',
      image: 'https://media.api-sports.io/formula-1/circuits/20.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-22T19:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1586,
    competition: {
      id: 20,
      name: 'USA Grand Prix',
      location: { country: 'USA', city: 'Elroy' },
    },
    circuit: {
      id: 20,
      name: 'Circuit of The Americas',
      image: 'https://media.api-sports.io/formula-1/circuits/20.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-21T22:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1587,
    competition: {
      id: 20,
      name: 'USA Grand Prix',
      location: { country: 'USA', city: 'Elroy' },
    },
    circuit: {
      id: 20,
      name: 'Circuit of The Americas',
      image: 'https://media.api-sports.io/formula-1/circuits/20.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-10-21T19:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1588,
    competition: {
      id: 21,
      name: 'Mexico Grand Prix',
      location: { country: 'Mexico', city: 'Mexico' },
    },
    circuit: {
      id: 21,
      name: 'Autódromo Hermanos Rodríguez',
      image: 'https://media.api-sports.io/formula-1/circuits/21.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 71 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '308.9 Kms',
    timezone: 'utc',
    date: '2022-11-30T19:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1589,
    competition: {
      id: 21,
      name: 'Mexico Grand Prix',
      location: { country: 'Mexico', city: 'Mexico' },
    },
    circuit: {
      id: 21,
      name: 'Autódromo Hermanos Rodríguez',
      image: 'https://media.api-sports.io/formula-1/circuits/21.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-29T20:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1590,
    competition: {
      id: 21,
      name: 'Mexico Grand Prix',
      location: { country: 'Mexico', city: 'Mexico' },
    },
    circuit: {
      id: 21,
      name: 'Autódromo Hermanos Rodríguez',
      image: 'https://media.api-sports.io/formula-1/circuits/21.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-29T17:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1591,
    competition: {
      id: 21,
      name: 'Mexico Grand Prix',
      location: { country: 'Mexico', city: 'Mexico' },
    },
    circuit: {
      id: 21,
      name: 'Autódromo Hermanos Rodríguez',
      image: 'https://media.api-sports.io/formula-1/circuits/21.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-28T21:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1592,
    competition: {
      id: 21,
      name: 'Mexico Grand Prix',
      location: { country: 'Mexico', city: 'Mexico' },
    },
    circuit: {
      id: 21,
      name: 'Autódromo Hermanos Rodríguez',
      image: 'https://media.api-sports.io/formula-1/circuits/21.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-28T18:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1593,
    competition: {
      id: 22,
      name: 'Brazil Grand Prix',
      location: { country: 'Brazil', city: 'São Paulo' },
    },
    circuit: {
      id: 22,
      name: 'Autódromo José Carlos Pace',
      image: 'https://media.api-sports.io/formula-1/circuits/22.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 71 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '305.9 Kms',
    timezone: 'utc',
    date: '2022-11-13T18:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1595,
    competition: {
      id: 22,
      name: 'Brazil Grand Prix',
      location: { country: 'Brazil', city: 'São Paulo' },
    },
    circuit: {
      id: 22,
      name: 'Autódromo José Carlos Pace',
      image: 'https://media.api-sports.io/formula-1/circuits/22.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-12T15:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1596,
    competition: {
      id: 22,
      name: 'Brazil Grand Prix',
      location: { country: 'Brazil', city: 'São Paulo' },
    },
    circuit: {
      id: 22,
      name: 'Autódromo José Carlos Pace',
      image: 'https://media.api-sports.io/formula-1/circuits/22.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-11T19:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1597,
    competition: {
      id: 22,
      name: 'Brazil Grand Prix',
      location: { country: 'Brazil', city: 'São Paulo' },
    },
    circuit: {
      id: 22,
      name: 'Autódromo José Carlos Pace',
      image: 'https://media.api-sports.io/formula-1/circuits/22.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-11T15:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1598,
    competition: {
      id: 23,
      name: 'Abu Dhabi Grand Prix',
      location: { country: 'Abu Dhabi', city: 'Yas Marina, Abou Dabi ' },
    },
    circuit: {
      id: 23,
      name: 'Yas Marina Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/23.png',
    },
    season: 2022,
    type: 'Race',
    laps: { current: null, total: 55 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-11-20T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1599,
    competition: {
      id: 23,
      name: 'Abu Dhabi Grand Prix',
      location: { country: 'Abu Dhabi', city: 'Yas Marina, Abou Dabi ' },
    },
    circuit: {
      id: 23,
      name: 'Yas Marina Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/23.png',
    },
    season: 2022,
    type: '1st Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-19T14:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1600,
    competition: {
      id: 23,
      name: 'Abu Dhabi Grand Prix',
      location: { country: 'Abu Dhabi', city: 'Yas Marina, Abou Dabi ' },
    },
    circuit: {
      id: 23,
      name: 'Yas Marina Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/23.png',
    },
    season: 2022,
    type: '3rd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-19T11:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1601,
    competition: {
      id: 23,
      name: 'Abu Dhabi Grand Prix',
      location: { country: 'Abu Dhabi', city: 'Yas Marina, Abou Dabi ' },
    },
    circuit: {
      id: 23,
      name: 'Yas Marina Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/23.png',
    },
    season: 2022,
    type: '2nd Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-18T13:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1602,
    competition: {
      id: 23,
      name: 'Abu Dhabi Grand Prix',
      location: { country: 'Abu Dhabi', city: 'Yas Marina, Abou Dabi ' },
    },
    circuit: {
      id: 23,
      name: 'Yas Marina Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/23.png',
    },
    season: 2022,
    type: '1st Practice',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-11-18T10:00:00+00:00',
    weather: null,
    status: 'Scheduled',
  },
  {
    id: 1603,
    competition: {
      id: 2,
      name: 'Bahrain Grand Prix',
      location: { country: 'Bahrain', city: 'Sakhir' },
    },
    circuit: {
      id: 2,
      name: 'Bahrain International Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/2.png',
    },
    season: 2022,
    type: '3rd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-19T15:42:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1604,
    competition: {
      id: 2,
      name: 'Bahrain Grand Prix',
      location: { country: 'Bahrain', city: 'Sakhir' },
    },
    circuit: {
      id: 2,
      name: 'Bahrain International Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/2.png',
    },
    season: 2022,
    type: '2nd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-19T15:21:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1612,
    competition: {
      id: 32,
      name: 'Saudi Arabia Grand Prix',
      location: { country: 'Saudi Arabia ', city: 'Djeddah' },
    },
    circuit: {
      id: 29,
      name: 'Jeddah Corniche Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/29.png',
    },
    season: 2022,
    type: '3rd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-26T17:42:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1613,
    competition: {
      id: 32,
      name: 'Saudi Arabia Grand Prix',
      location: { country: 'Saudi Arabia ', city: 'Djeddah' },
    },
    circuit: {
      id: 29,
      name: 'Jeddah Corniche Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/29.png',
    },
    season: 2022,
    type: '2nd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-03-26T17:21:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1621,
    competition: {
      id: 1,
      name: 'Australia Grand Prix',
      location: { country: 'Australia', city: 'Melbourne' },
    },
    circuit: {
      id: 1,
      name: 'Albert Park Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/1.png',
    },
    season: 2022,
    type: '3rd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-09T06:42:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1622,
    competition: {
      id: 1,
      name: 'Australia Grand Prix',
      location: { country: 'Australia', city: 'Melbourne' },
    },
    circuit: {
      id: 1,
      name: 'Albert Park Circuit',
      image: 'https://media.api-sports.io/formula-1/circuits/1.png',
    },
    season: 2022,
    type: '2nd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-09T06:21:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1623,
    competition: {
      id: 29,
      name: 'Emilia Romagna Grand Prix',
      location: { country: 'Italy', city: 'Imola' },
    },
    circuit: {
      id: 27,
      name: 'Autodromo Enzo e Dino Ferrari',
      image: 'https://media.api-sports.io/formula-1/circuits/27.png',
    },
    season: 2022,
    type: 'Sprint',
    laps: { current: null, total: 57 },
    fastest_lap: { driver: { id: null }, time: null },
    distance: '307.6 Kms',
    timezone: 'utc',
    date: '2022-04-23T14:30:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1624,
    competition: {
      id: 29,
      name: 'Emilia Romagna Grand Prix',
      location: { country: 'Italy', city: 'Imola' },
    },
    circuit: {
      id: 27,
      name: 'Autodromo Enzo e Dino Ferrari',
      image: 'https://media.api-sports.io/formula-1/circuits/27.png',
    },
    season: 2022,
    type: '3rd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-22T15:42:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1625,
    competition: {
      id: 29,
      name: 'Emilia Romagna Grand Prix',
      location: { country: 'Italy', city: 'Imola' },
    },
    circuit: {
      id: 27,
      name: 'Autodromo Enzo e Dino Ferrari',
      image: 'https://media.api-sports.io/formula-1/circuits/27.png',
    },
    season: 2022,
    type: '2nd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-04-22T15:21:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1626,
    competition: {
      id: 34,
      name: 'Miami Grand Prix',
      location: { country: 'USA', city: 'Miami' },
    },
    circuit: {
      id: 31,
      name: 'Miami International Autodrome',
      image: 'https://media.api-sports.io/formula-1/circuits/31.png',
    },
    season: 2022,
    type: '3rd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-07T20:42:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1627,
    competition: {
      id: 34,
      name: 'Miami Grand Prix',
      location: { country: 'USA', city: 'Miami' },
    },
    circuit: {
      id: 31,
      name: 'Miami International Autodrome',
      image: 'https://media.api-sports.io/formula-1/circuits/31.png',
    },
    season: 2022,
    type: '2nd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-07T20:21:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1628,
    competition: {
      id: 6,
      name: 'Spain Grand Prix',
      location: { country: 'Spain', city: ' Montmeló' },
    },
    circuit: {
      id: 6,
      name: 'Circuit de Barcelona-Catalunya',
      image: 'https://media.api-sports.io/formula-1/circuits/6.png',
    },
    season: 2022,
    type: '3rd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-21T14:42:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1629,
    competition: {
      id: 6,
      name: 'Spain Grand Prix',
      location: { country: 'Spain', city: ' Montmeló' },
    },
    circuit: {
      id: 6,
      name: 'Circuit de Barcelona-Catalunya',
      image: 'https://media.api-sports.io/formula-1/circuits/6.png',
    },
    season: 2022,
    type: '2nd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-21T14:21:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1630,
    competition: {
      id: 7,
      name: 'Monaco Grand Prix',
      location: { country: 'Monaco', city: 'Monte-Carlo' },
    },
    circuit: {
      id: 7,
      name: 'Circuit de Monaco',
      image: 'https://media.api-sports.io/formula-1/circuits/7.png',
    },
    season: 2022,
    type: '3rd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-28T14:42:00+00:00',
    weather: null,
    status: 'Completed',
  },
  {
    id: 1631,
    competition: {
      id: 7,
      name: 'Monaco Grand Prix',
      location: { country: 'Monaco', city: 'Monte-Carlo' },
    },
    circuit: {
      id: 7,
      name: 'Circuit de Monaco',
      image: 'https://media.api-sports.io/formula-1/circuits/7.png',
    },
    season: 2022,
    type: '2nd Qualifying',
    laps: { current: null, total: null },
    fastest_lap: { driver: { id: null }, time: null },
    distance: null,
    timezone: 'utc',
    date: '2022-05-28T14:21:00+00:00',
    weather: null,
    status: 'Completed',
  },
];

const mapRaces = (races: RaceData[]) => {
  return races.reduce<MapedRace[]>((acc, race) => {
    const correctedType = race.type.includes('Qualifying')
      ? 'Qualifying'
      : race.type;

    const event = {
      type: correctedType,
      date: race.date,
      timezone: race.timezone,
    };

    const currentRace: MapedRace | undefined = acc.find(
      (e) => e.competition.id === race.competition.id
    );

    if (currentRace != null) {
      if (
        event.type === 'Qualifying' &&
        currentRace.events.some((e) => e.type.includes('Qualifying'))
      ) {
        return acc;
      }
      const newCurrentRace = {
        ...currentRace,
        events: [...currentRace.events, event],
      };

      const newAcc = acc.filter(
        (e) => e.competition.id !== race.competition.id
      );

      return [...newAcc, newCurrentRace];
    }
    const mapedRace = [{ ...race, events: [event] }];
    return [...acc, ...mapedRace];
  }, []);
};

export const makeRaces = (races: RaceData[] | null) => {
  if (races == null) return null;

  const filteredRaces = races.filter((e) => e.status !== 'Cancelled');
  const mapedRaces = mapRaces(filteredRaces);

  const orderedRaces = mapedRaces.sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  );

  const finalRaces = orderedRaces.map((e, index) => ({
    ...e,
    round: index + 1,
  }));

  return finalRaces;
};

export default async function getRaces(timezone: string): Promise<GetRaces> {
  const currentTimezone = timezone === 'Your Time' ? 'Europe/Rome' : timezone;

  const { data, errors } = await getData<RaceData[]>(races, 'races', {
    season: '2023',
    timezone: currentTimezone,
  });

  return { data: makeRaces(data), errors };
}
