import getData from '@/lib/getData';

export type Team = {
  id: number;
  name: string;
  logo: string;
  base: string | null;
  first_team_entry: number | null;
  world_championships: number | null;
  highest_race_finish: { position: number | null; number: number | null };
  pole_positions: number | null;
  fastest_laps: number | null;
  president: string;
  director: string;
  technical_manager: string | null;
  chassis: string | null;
  engine: string;
  tyres: string;
};

type GetTeam = { data: Team[] | null; errors: string | null };

const teams: Team[] = [
  {
    id: 1,
    name: 'Red Bull Racing',
    logo: 'https://media.api-sports.io/formula-1/teams/1.png',
    base: 'Milton Keynes, United Kingdom',
    first_team_entry: 1997,
    world_championships: 4,
    highest_race_finish: { position: 1, number: 79 },
    pole_positions: 75,
    fastest_laps: 79,
    president: 'Dietrich Mateschitz',
    director: 'Christian Horner',
    technical_manager: 'Pierre Waché',
    chassis: 'RB18',
    engine: 'Red Bull Powertrains',
    tyres: 'Pirelli',
  },
  {
    id: 2,
    name: 'McLaren Racing',
    logo: 'https://media.api-sports.io/formula-1/teams/2.png',
    base: 'Woking, United Kingdom',
    first_team_entry: 1966,
    world_championships: 8,
    highest_race_finish: { position: 1, number: 183 },
    pole_positions: 156,
    fastest_laps: 160,
    president: 'Zak Brown',
    director: 'Andreas Seidl',
    technical_manager: 'James Key',
    chassis: 'MCL36',
    engine: 'Mercedes',
    tyres: 'Pirelli',
  },
  {
    id: 3,
    name: 'Scuderia Ferrari',
    logo: 'https://media.api-sports.io/formula-1/teams/3.png',
    base: 'Maranello, Italy',
    first_team_entry: 1950,
    world_championships: 16,
    highest_race_finish: { position: 1, number: 241 },
    pole_positions: 234,
    fastest_laps: 256,
    president: 'John Elkann',
    director: 'Mattia Binotto',
    technical_manager: 'Enrico Cardile / Enrico Gualtieri',
    chassis: 'F1-75',
    engine: 'Ferrari',
    tyres: 'Pirelli',
  },
  {
    id: 4,
    name: 'Force India',
    logo: 'https://media.api-sports.io/formula-1/teams/4.png',
    base: null,
    first_team_entry: null,
    world_championships: null,
    highest_race_finish: { position: null, number: null },
    pole_positions: null,
    fastest_laps: null,
    president: 'Subrata Roy, Vijay Mallya',
    director: 'Robert Fernley',
    technical_manager: 'Andrew Green',
    chassis: null,
    engine: 'Ferrari V8, Mercedes V8, Mercedes V6 turbo',
    tyres: 'Bridgestone, Pirelli',
  },
  {
    id: 5,
    name: 'Mercedes-AMG Petronas',
    logo: 'https://media.api-sports.io/formula-1/teams/5.png',
    base: 'Brackley, United Kingdom',
    first_team_entry: 1970,
    world_championships: 8,
    highest_race_finish: { position: 1, number: 115 },
    pole_positions: 127,
    fastest_laps: 85,
    president: 'Markus Schäfer',
    director: 'Toto Wolff',
    technical_manager: 'Mike Elliott',
    chassis: 'W13',
    engine: 'Mercedes',
    tyres: 'Pirelli',
  },
  {
    id: 6,
    name: 'Lotus F1 Team',
    logo: 'https://media.api-sports.io/formula-1/teams/6.png',
    base: null,
    first_team_entry: null,
    world_championships: null,
    highest_race_finish: { position: null, number: null },
    pole_positions: null,
    fastest_laps: null,
    president: 'Gérard Lopez, Éric Lux,Andrew Ruhan',
    director: 'Éric Boullier, Matthew Carter',
    technical_manager: 'James Allison, Nick Chester',
    chassis: null,
    engine: 'Mercedes',
    tyres: 'Pirelli',
  },
  {
    id: 7,
    name: 'Scuderia AlphaTauri Honda',
    logo: 'https://media.api-sports.io/formula-1/teams/7.png',
    base: 'Faenza, Italy',
    first_team_entry: 1985,
    world_championships: 0,
    highest_race_finish: { position: 1, number: 2 },
    pole_positions: 1,
    fastest_laps: 2,
    president: 'Dietrich Mateschitz',
    director: 'Franz Tost',
    technical_manager: 'Jody Egginton',
    chassis: 'AT03',
    engine: 'Red Bull Powertrains',
    tyres: 'Pirelli',
  },
  {
    id: 8,
    name: 'Sauber F1 Team',
    logo: 'https://media.api-sports.io/formula-1/teams/8.png',
    base: null,
    first_team_entry: null,
    world_championships: null,
    highest_race_finish: { position: null, number: null },
    pole_positions: null,
    fastest_laps: null,
    president: 'Pascal Picci',
    director: 'Frédéric Vasseur',
    technical_manager: 'Simone Resta',
    chassis: null,
    engine: 'Ferrari V6 turbo Type 062 EVO',
    tyres: 'Pirelli',
  },
  {
    id: 9,
    name: 'Manor Marussia F1 Team',
    logo: 'https://media.api-sports.io/formula-1/teams/9.png',
    base: null,
    first_team_entry: null,
    world_championships: null,
    highest_race_finish: { position: null, number: null },
    pole_positions: null,
    fastest_laps: null,
    president: 'Stephen Fitzpatrick',
    director: 'Abdulla Boulsien',
    technical_manager: 'John McQuilliam',
    chassis: null,
    engine: 'Cosworth, Ferrari',
    tyres: 'Pirelli',
  },
  {
    id: 10,
    name: 'Caterham F1 Team',
    logo: 'https://media.api-sports.io/formula-1/teams/10.png',
    base: null,
    first_team_entry: null,
    world_championships: null,
    highest_race_finish: { position: null, number: null },
    pole_positions: null,
    fastest_laps: null,
    president:
      "Tony Fernandes, Graham Macdonald, Colin Kolles, Finbarr O'Connell",
    director:
      'Riad Asmat, Steve Nielsen, Cyril Abiteboul, Christijan Albers, Manfredi Ravetto',
    technical_manager: 'Mike Gascoyne, Mark Smith, John Iley',
    chassis: null,
    engine: 'Renault',
    tyres: 'Pirelli',
  },
  {
    id: 11,
    name: 'HRT Formula One Team',
    logo: 'https://media.api-sports.io/formula-1/teams/11.png',
    base: null,
    first_team_entry: null,
    world_championships: null,
    highest_race_finish: { position: null, number: null },
    pole_positions: null,
    fastest_laps: null,
    president: 'Saul Ruiz de Marcos',
    director: 'Luis Pérez-Sala',
    technical_manager: 'Toni Cuquerella',
    chassis: null,
    engine: 'Cosworth',
    tyres: 'Bridgestone, Pirelli',
  },
  {
    id: 12,
    name: 'Williams F1 Team',
    logo: 'https://media.api-sports.io/formula-1/teams/12.png',
    base: 'Grove, United Kingdom',
    first_team_entry: 1978,
    world_championships: 9,
    highest_race_finish: { position: 1, number: 114 },
    pole_positions: 128,
    fastest_laps: 133,
    president: 'Claire Williams',
    director: 'Jost Capito',
    technical_manager: 'François-Xavier Demaison',
    chassis: 'FW44',
    engine: 'Mercedes',
    tyres: 'Pirelli',
  },
  {
    id: 13,
    name: 'Alpine F1 Team',
    logo: 'https://media.api-sports.io/formula-1/teams/13.png',
    base: 'Enstone, United Kingdom',
    first_team_entry: 1986,
    world_championships: 2,
    highest_race_finish: { position: 1, number: 21 },
    pole_positions: 20,
    fastest_laps: 15,
    president: 'Alain Prost, Jérôme Stoll ',
    director: 'Otmar Szafnauer',
    technical_manager: 'Pat Fry',
    chassis: 'A522',
    engine: 'Renault',
    tyres: 'Pirelli',
  },
  {
    id: 14,
    name: 'Haas F1 Team',
    logo: 'https://media.api-sports.io/formula-1/teams/14.png',
    base: 'Kannapolis, United States',
    first_team_entry: 2016,
    world_championships: 0,
    highest_race_finish: { position: 4, number: 1 },
    pole_positions: 0,
    fastest_laps: 2,
    president: 'Gene Haas',
    director: 'Guenther Steiner',
    technical_manager: 'Simone Resta',
    chassis: 'VF-22',
    engine: 'Ferrari',
    tyres: 'Pirelli',
  },
  {
    id: 15,
    name: 'Virgin Racing',
    logo: 'https://media.api-sports.io/formula-1/teams/15.png',
    base: null,
    first_team_entry: null,
    world_championships: null,
    highest_race_finish: { position: null, number: null },
    pole_positions: null,
    fastest_laps: null,
    president: 'Richard Branson',
    director: 'Alex Tai',
    technical_manager: null,
    chassis: null,
    engine: 'Spark SRT_01E Renault',
    tyres: 'Michelin',
  },
  {
    id: 16,
    name: 'Manor Racing',
    logo: 'https://media.api-sports.io/formula-1/teams/16.png',
    base: null,
    first_team_entry: null,
    world_championships: null,
    highest_race_finish: { position: null, number: null },
    pole_positions: null,
    fastest_laps: null,
    president: 'Stephen Fitzpatrick',
    director: 'Thomas Mayer',
    technical_manager: 'John McQuilliam, Nikolas Tombazis',
    chassis: null,
    engine: 'Mercedes V6 turbo hybride',
    tyres: 'Pirelli',
  },
  {
    id: 17,
    name: 'Aston Martin F1 Team',
    logo: 'https://media.api-sports.io/formula-1/teams/17.png',
    base: 'Silverstone, United Kingdom',
    first_team_entry: 2018,
    world_championships: 0,
    highest_race_finish: { position: 1, number: 1 },
    pole_positions: 1,
    fastest_laps: 0,
    president: 'Lawrence Stroll',
    director: 'Mike Krack',
    technical_manager: 'Andrew Green',
    chassis: 'AMR22',
    engine: 'Mercedes',
    tyres: 'Pirelli',
  },
  {
    id: 18,
    name: 'Alfa Romeo',
    logo: 'https://media.api-sports.io/formula-1/teams/18.png',
    base: 'Hinwil, Switzerland',
    first_team_entry: 1993,
    world_championships: 0,
    highest_race_finish: { position: 1, number: 1 },
    pole_positions: 1,
    fastest_laps: 5,
    president: 'Pascal Picci',
    director: 'Frédéric Vasseur',
    technical_manager: 'Jan Monchaux',
    chassis: 'C42',
    engine: 'Ferrari',
    tyres: 'Pirelli',
  },
];

export default async function getTeams(): Promise<GetTeam> {
  return await getData<Team[]>(teams, 'teams');
}
